### ISSUE TITLE
What is your setup for the screenshot in the README?

### ISSUE THREAD

**Issue by tekknolagi** [jansedivy/jai.vim#1]
It looks quite good.

**Comment by jansedivy** [comment]
Hey Max,

It's just iTerm running Vim with this [configuration](https://github.com/jansedivy/dotfiles/blob/master/config/nvim.symlink/init.vim)
The color theme is [vim-hybrid](https://github.com/w0ng/vim-hybrid) using Inconsolata-g font

**Comment by tekknolagi** [comment]
Neat, thanks!
