### ISSUE TITLE
Request to be added to collaborators

### ISSUE THREAD

**Issue by BenFradella** [jansedivy/jai.vim#3]
Made a branch to merge in @rluba's fork and a small change of my own, but got this error trying to push up my branch:
```
$ git push -v --set-upstream origin merge-fork
Pushing to github.com:rluba/jai.vim.git
ERROR: Permission to rluba/jai.vim.git denied to BenFradella.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by rluba** [comment]
@BenFradella feel free to submit a PR with your changes to my fork.

**Comment by BenFradella** [comment]
@rluba I get the same error pushing a branch to your fork

**Comment by rluba** [comment]
That’s not how PRs work. You might want to google that. Push to your own fork, then submit a PR from there.

**Comment by BenFradella** [comment]
Made a PR. Thanks for pointing that out -- I didn't realize github required forking a repo to start contributing
