### ISSUE TITLE
break and continue missing as keywords.

### ISSUE THREAD

**Issue by mcourteaux** [jansedivy/jai.vim#4]

**Comment by jansedivy** [comment]
Hey! Thanks for reporting this! There are probably a lot of keywords missing that need to be aded.

`continue` and `break` is now included.

https://github.com/jansedivy/jai.vim/commit/05c7f35e202f7973125161ee4ea246bd15ab97f4

**Comment by mcourteaux** [comment]
Thanks! I was lazy and didn't have time to fork, clone, fix, push, and make PR yesterday. But wanted to quickly formalize that those were missing, and move on. Usually I make PRs for stuff like this. Thanks!

**Comment by mcourteaux** [comment]
`remove`, `case`, `ifx` missing too.
